"""Immutable projection of one completed Derived analysis event."""
import hashlib,json
from models.derived_paper_models import DerivedDecisionSnapshot

def build_derived_signal_snapshot(*,provider_symbol,display_name,family,subfamily,requested_strategy,analysis_candle_time,decision_contract,data_snapshot_id=""):
    decision=decision_contract.get("decision") or {};plan=decision_contract.get("active_trade_plan") or {};router=decision_contract.get("auto_evaluation") or {};strategy=router.get("selected_strategy") or decision.get("strategy");setup_id=decision.get("setup_id");created=str(analysis_candle_time);dedupe_parts=[provider_symbol,"M5",created,requested_strategy,setup_id,decision.get("status")];dedupe=hashlib.sha256(json.dumps(dedupe_parts,default=str).encode()).hexdigest();decision_id="paper-decision-"+dedupe[:24]
    payload={"decision_id":decision_id,"created_at":created,"analysis_candle_time":created,"provider":"deriv","provider_symbol":provider_symbol,"display_name":display_name,"family":family,"subfamily":subfamily,"requested_strategy":requested_strategy,"selected_strategy":strategy,"setup_id":setup_id,"range_id":decision.get("range_id"),"spike_id":decision.get("spike_id"),"event_id":decision.get("event_id"),"decision":{key:decision.get(key) for key in ("status","market_bias","developing_direction","trade_ready","summary","next_action","setup_stage")},"market_context":{"regime":decision.get("regime"),"volatility_regime":(decision_contract.get("market_profile") or {}).get("volatility_regime"),"spike_state":(decision_contract.get("spike_state") or {}).get("classification"),"top_down_alignment":"","data_quality":((decision_contract.get("advanced_details") or {}).get("data_quality") or {}).get("status")},"setup":{"state":decision.get("status"),"m15_zone":decision_contract.get("m15_setup_zone"),"m5_zone":decision_contract.get("m5_execution_zone"),"confirmation":decision_contract.get("confirmation"),"entry":plan.get("entry"),"stop":plan.get("stop"),"tp1":plan.get("tp1"),"tp2":plan.get("tp2"),"tp1_rr":plan.get("tp1_rr"),"tp2_rr":plan.get("tp2_rr"),"timing_state":plan.get("timing_state"),"entry_type":plan.get("entry_type","confirmation_close")},"router":{"eligible_strategies":router.get("eligible_strategies",[]),"selected_strategy":strategy,"selection_reason":router.get("selection_reason",""),"selection_confidence":router.get("selection_confidence"),"runner_up":((decision_contract.get("auto_diagnostics") or {}).get("runner_up"))},"evidence":((decision_contract.get("advanced_details") or {}).get("regime") or {}).get("evidence",[]),"contradictions":((decision_contract.get("advanced_details") or {}).get("regime") or {}).get("contradictions",[]),"warnings":decision_contract.get("warnings",[]),"data_snapshot_id":data_snapshot_id,"research_mode":bool(decision.get("paper_analysis_only") or decision_contract.get("research_mode"))}
    if decision_contract.get("ownership"):
        payload["smc_contract"]={key:decision_contract.get(key) for key in ("ownership","setup","structure","liquidity","swings","displacements","fvgs","order_blocks","dealing_range","event","expected_next_event_direction","evaluated_candidates","scoring","gate_funnel","invariants","trade_chart","target_trace","target_source_audit","history_depth_audit")}
        payload["normalized_decision"]=decision_contract.get("product_contract")
    return DerivedDecisionSnapshot(decision_id,dedupe,created,created,provider_symbol,family,strategy,setup_id,payload)
