from __future__ import annotations
import html,json
from statistics import median
from paper_testing.derived_performance_aggregator import chronological_drawdown
from validation.smc_evidence import classify_acceptance_evidence

def build_acceptance_report(*,dataset,run,decisions,setups,outcomes,reachability,blockers,causality,invalid_plans,optional_confluence):
    ready=sum(((x.get("payload") or x).get("smc_contract") or {}).get("setup",{}).get("state")=="TRADE_READY" for x in decisions);resolved=[x for x in outcomes if x.get("outcome") not in {None,"OPEN"}];rs=[float(x["realized_r"]) for x in resolved if x.get("realized_r") is not None];directions={x.get("direction") for x in setups if x.get("direction")};regimes={((x.get("payload") or x).get("smc_contract") or {}).get("structure",{}).get("external_structure") for x in decisions};evidence=classify_acceptance_evidence(resolved_trades=len(resolved),periods=1,symbols=1,regimes=len(regimes-{None}),directions=len(directions-{None}));reached=[x["setup_type"] for x in reachability if x["reachable"]]
    symbol_row={"symbol":dataset["symbol"],"family":dataset["family"],"variant":dataset["variant"],"dataset_id":dataset["dataset_id"],"checksum":dataset["checksum"],"periods":1,"decisions":len(decisions),"developing_setups":sum(bool(((x.get("payload") or x).get("decision") or {}).get("developing_direction")) for x in decisions),"trade_ready_setups":ready,"filled_trades":sum(bool(x.get("entry_filled")) for x in outcomes),"resolved_trades":len(resolved),"setup_types_reached":reached,"unreachable_setup_types":[x["setup_type"] for x in reachability if not x["reachable"]],"most_common_blocker":max(blockers["first_blockers"],key=blockers["first_blockers"].get) if blockers["first_blockers"] else "","causality_violations":causality["violation_count"],"invalid_trade_plans":len(invalid_plans),"state_contradictions":sum(bool((((x.get("payload") or x).get("smc_contract") or {}).get("invariants") or {}).get("failures")) for x in decisions),"evidence":evidence["label"]}
    performance={"resolved_trades":len(resolved),"wins":sum(x>0 for x in rs),"losses":sum(x<0 for x in rs),"ambiguous_outcomes":sum(bool(x.get("intracandle_ambiguous")) for x in resolved),"average_r":sum(rs)/len(rs) if rs else None,"median_r":median(rs) if rs else None,"expectancy":sum(rs)/len(rs) if rs else None,"profit_factor":sum(x for x in rs if x>0)/abs(sum(x for x in rs if x<0)) if any(x<0 for x in rs) else None,"maximum_drawdown_r":chronological_drawdown(resolved)["maximum_drawdown_r"]}
    return {"symbols":[symbol_row],"dataset":dataset,"run":run,"reachability":reachability,"blocker_distribution":blockers,"causality":causality,"invalid_trade_plans":invalid_plans,"optional_confluence_audit":optional_confluence,"performance":performance,"evidence":evidence,"optimization_performed":False,"orders_placed":False}

def render_acceptance_html(report):
    symbol=report["symbols"][0];rows="".join(f"<tr><td>{html.escape(x['setup_type'])}</td><td>{x['context_count']}</td><td>{x['trade_ready_count']}</td><td>{x['filled_count']}</td><td>{html.escape(x['zero_trade_classification'])}</td></tr>" for x in report["reachability"]);return f"""<!doctype html><html><head><meta charset='utf-8'><title>TradeScor SMC Acceptance</title><style>body{{font:14px system-ui;background:#07111f;color:#dce8f7;padding:28px}}table{{border-collapse:collapse;width:100%}}td,th{{padding:8px;border-bottom:1px solid #24354b;text-align:left}}.ok{{color:#59d5a5}}.bad{{color:#ff8e8e}}</style></head><body><h1>SMC Historical Acceptance</h1><p>{html.escape(symbol['symbol'])} · {html.escape(symbol['family'])} · {html.escape(report['evidence']['label'])}</p><p>Dataset <code>{html.escape(symbol['dataset_id'])}</code> · checksum <code>{html.escape(symbol['checksum'])}</code></p><p class='{'ok' if not symbol['causality_violations'] else 'bad'}'>Causality violations: {symbol['causality_violations']} · Invalid plans: {symbol['invalid_trade_plans']}</p><table><thead><tr><th>Setup type</th><th>Context</th><th>Ready</th><th>Filled</th><th>Classification</th></tr></thead><tbody>{rows}</tbody></table><h2>Blockers</h2><pre>{html.escape(json.dumps(report['blocker_distribution'],indent=2))}</pre></body></html>"""
