from analysis.smc.smc_scoring import score_smc
from analysis.smc.smc_invariants import validate_smc_contract

def normalize_smc_result(*,requested_strategy,adapter_id,family,model_name,setup,structure,liquidity,swings,displacements,fvgs,order_blocks,dealing_range,event=None,candidates=None,selection_reason=""):
    requested=str(requested_strategy).lower();manual=requested not in {"auto","smc_auto"};selected=requested if manual else "smc_auto";owner=selected;ready=setup["state"]=="TRADE_READY" and not setup.get("research_only");direction=setup.get("direction","");target=setup.get("structural_target") or {};entry_array=setup.get("entry_array") or {};validity={"data_available":bool(swings),"state_consistent":not structure.get("structure_conflict"),"required_structure":structure.get("external_structure") in {"bullish","bearish"},"location_valid":bool(entry_array),"completed_confirmation":bool(setup.get("mss") or setup.get("bos")),"entry_geometry":setup.get("entry") is not None if ready else setup.get("state") not in {"TRADE_READY"},"stop_geometry":setup.get("stop") is not None if ready else True,"target_geometry":bool(target),"rr_passed":setup.get("projected_rr") is not None and setup.get("projected_rr")>=1.5 if setup.get("state") in {"TRADE_READY","WAITING_FOR_ENTRY_CONFIRMATION"} else True,"not_too_late":setup["state"]!="TOO_LATE"};quality={"htf_alignment":1 if structure.get("external_structure")==structure.get("internal_structure") else .5,"displacement_strength":min(1,(setup.get("displacement") or {}).get("body_atr",0)),"clean_sweep":1 if (setup.get("sweep") or {}).get("type")=="sweep" else .5,"fvg_quality":1 if fvgs else 0,"order_block_quality":max([x.get("quality_score",0) for x in order_blocks] or [0]),"premium_discount_alignment":.7 if dealing_range else 0,"target_clarity":1 if target else 0,"low_structural_conflict":0 if structure.get("structure_conflict") else 1};scoring=score_smc(validity,quality);ready=ready and scoring["valid"]
    if setup.get("state")=="TRADE_READY" and not scoring["valid"]:
        rejected_plan={"entry":setup.get("entry"),"stop":setup.get("stop"),"targets":setup.get("targets"),"rr":setup.get("rr")};setup.update({"state":"PLAN REJECTED","entry":None,"stop":None,"targets":[],"rr":None,"next_required_condition":"The complete plan failed an essential quality or context gate."})
    else:rejected_plan=None
    status=("READY TO BUY" if direction=="buy" else "READY TO SELL") if ready else "PLAN REJECTED" if setup.get("state")=="PLAN REJECTED" else "NO TRADE PLAN";plan={"direction":direction,"entry":setup["entry"],"stop":setup["stop"],"tp1":setup["targets"][0]["price"],"tp2":setup["targets"][1]["price"] if len(setup["targets"])>1 else None,"tp1_rr":setup["rr"],"timing_state":"VALID"} if ready else None;zone={"low":entry_array.get("low"),"high":entry_array.get("high"),"type":entry_array.get("type","smc_pd_array"),"valid":bool(entry_array)} if entry_array else None
    ownership={"requested_strategy_id":str(requested_strategy).lower(),"selected_strategy_id":selected,"decision_owner_id":owner,"overlay_owner_id":owner,"adapter_id":adapter_id,"selection_mode":"manual" if manual else "auto","selection_reason":selection_reason or f"{model_name} is the registry-supported SMC adapter for {family.get('family')}."}
    decision={"status":status,"market_bias":"bullish" if direction=="buy" else "bearish" if direction=="sell" else "neutral" if structure.get("external_structure") in {"range",None} else structure.get("external_structure","neutral"),"developing_direction":direction,"trade_ready":ready,"setup_id":setup["setup_id"],"strategy":selected,"strategy_label":model_name,"setup_stage":setup["state"],"summary":status.title(),"next_action":setup["next_required_condition"],"regime":structure.get("external_structure","transition"),"paper_analysis_only":True}
    chart={"owner_id":owner,"idea":direction or "none","state":"entry_available" if ready else "developing" if zone else "none","current_price":None,"m15_setup_zone":zone or {"low":None,"high":None,"type":""},"m5_execution_zone":zone or {"low":None,"high":None,"type":""},"confirmation":{"price":None,"confirmed":bool(setup.get("mss") or setup.get("bos")),"timeframe":"M5"},"confirmed_entry":setup.get("entry") if ready else None,"stop":setup.get("stop") if ready else None,"targets":setup.get("targets") if ready else [],"structural_liquidity_target":target,"confirmed_sweep":setup.get("sweep") if (setup.get("sweep") or {}).get("qualified") else None,"active_external_range":dealing_range,"message":setup["next_required_condition"]}
    result={"ownership":ownership,"decision":decision,"setup":setup,"structure":structure,"liquidity":liquidity,"swings":swings,"displacements":displacements,"fvgs":fvgs,"order_blocks":order_blocks,"dealing_range":dealing_range,"event":event,"evaluated_candidates":candidates or [],"scoring":scoring,"active_trade_plan":plan,"m15_setup_zone":zone,"m5_execution_zone":zone,"confirmation":setup.get("mss") or setup.get("bos"),"trade_chart":chart,"shadow_candidate":None if ready else {"strategy":selected,"direction":direction,"setup_stage":setup["state"],"first_blocking_gate":scoring["essential_failures"][0] if scoring["essential_failures"] else setup["state"],"research_only":True,"actionable_levels":None}}
    if rejected_plan:result["rejected_plan"]=rejected_plan
    result.update({"target_trace":setup.get("target_trace") or {},"target_source_audit":setup.get("target_source_audit") or {},"history_depth_audit":setup.get("history_depth_audit") or {}})
    result["invariants"]=validate_smc_contract(result)
    if not result["invariants"]["valid"]:
        corrected=result["invariants"].get("corrected_status") or "STATE CONTRADICTION";result["active_trade_plan"]=None;result["decision"].update({"status":corrected,"trade_ready":False,"summary":corrected.title(),"next_action":result["invariants"]["corrective_action"]});result["trade_chart"].update({"state":"none","confirmed_entry":None,"stop":None,"targets":[]})
        if setup.get("state")=="TRADE_READY":
            result["rejected_plan"]={"entry":setup.get("entry"),"stop":setup.get("stop"),"targets":setup.get("targets"),"rr":setup.get("rr")};setup.update({"state":corrected,"entry":None,"stop":None,"targets":[],"rr":None})
    return result
