GATES=("family_compatibility","history","external_structure","internal_structure","structural_target","setup_location","sweep_event","displacement","mss_bos_confirmation","entry_array","entry_geometry","stop_geometry","target_geometry","reward_to_risk","chase","lifecycle_validity")

def build_smc_gate_funnel(result,history=None):
    setup=result.get("setup") or {};structure=result.get("structure") or {};history=history or {};required={"D1":0,"H4":0,"H1":1,"M15":1,"M5":1};entry_array=setup.get("entry_array") or {};ready=setup.get("state")=="TRADE_READY";leg=structure.get("active_leg") or {};has_structure=bool(leg.get("low") or leg.get("high"));external=structure.get("external_structure");internal=structure.get("internal_structure")
    checks={"family_compatibility":True,"history":all(history.get(key,0)>=needed for key,needed in required.items()),"external_structure":external in {"bullish","bearish"} or external=="range" and has_structure,"internal_structure":internal in {"bullish","bearish"} or internal=="range" and has_structure,"structural_target":bool(setup.get("structural_target")),"setup_location":bool(entry_array),"sweep_event":bool((setup.get("sweep") or {}).get("qualified") or setup.get("bos")),"displacement":bool((setup.get("displacement") or {}).get("passed")),"mss_bos_confirmation":bool(setup.get("mss") or setup.get("bos")),"entry_array":bool(entry_array),"entry_geometry":setup.get("entry") is not None if ready else False,"stop_geometry":setup.get("stop") is not None if ready else False,"target_geometry":bool(setup.get("targets")) if ready else bool(setup.get("structural_target")),"reward_to_risk":setup.get("rr") is not None if ready else False,"chase":setup.get("state")!="TOO_LATE","lifecycle_validity":setup.get("state") not in {"INVALIDATED","CLOSED"}}
    rows={key:{"passed":bool(checks[key]),"reason":_reason(key,checks[key])} for key in GATES};rows["history"].update(available=history,required=required);first=next((key for key in GATES if not checks[key]),"");shadow=result.get("shadow_candidate")
    return {"strategy":result.get("ownership",{}).get("decision_owner_id"),**rows,"first_blocking_gate":first,"passed_gate_count":sum(checks.values()),"total_gate_count":len(GATES),"setup_stage":setup.get("state"),"next_price_condition":setup.get("next_required_condition"),"shadow_candidate":shadow,"current_values":{"projected_rr":setup.get("projected_rr")},"required_values":{"minimum_rr":1.5},"state_contradictions":(result.get("invariants") or {}).get("failures",[])}

def _reason(key,passed):return (key.replace("_"," ").title()+" passed.") if passed else (key.replace("_"," ").title()+" is the next unavailable essential condition.")
