import hashlib,json

STATES=("NO_CONTEXT","HTF_STRUCTURE_IDENTIFIED","DIRECTIONAL_CONTEXT","WAITING_FOR_TARGET","STRUCTURAL_TARGET_IDENTIFIED","WAITING_FOR_BOUNDARY","WAITING_FOR_SWEEP","SWEEP_DETECTED","WAITING_FOR_DISPLACEMENT","DISPLACEMENT_CONFIRMED","MSS_CONFIRMED","PD_ARRAY_SELECTED","WAITING_FOR_RETRACE","IN_ENTRY_AREA","WAITING_FOR_ENTRY_CONFIRMATION","TRADE_READY","PLAN REJECTED","TOO_LATE","INVALIDATED","FILLED","CLOSED")

def build_smc_setup(*,symbol,strategy_id,family_adapter,direction,htf_structure,structural_target=None,secondary_target=None,sweep=None,displacement=None,structure=None,entry_array=None,current_price=None,tick_size=.01,minimum_rr=1.5,event_risk=None,research_only=False):
    sweep=sweep or {};displacement=displacement or {};structure=structure or {};target=structural_target or {};entry_array=entry_array or {};event_ok=bool(sweep.get("qualified") or (structure.get("last_bos") and structure["last_bos"].get("direction")==direction));confirmation=(structure.get("last_mss") or structure.get("last_bos")) if direction in {"bullish","bearish"} else None;array_valid=bool(entry_array and not entry_array.get("invalidated"));entry=(float(entry_array["low"])+float(entry_array["high"]))/2 if array_valid else None;buffer=max(float(tick_size)*2,abs(float(entry_array.get("high",0))-float(entry_array.get("low",0)))*.1) if array_valid else None
    stop=(min(float(entry_array["low"]),float(sweep.get("extreme",entry_array["low"] if array_valid else 0)))-buffer) if direction=="bullish" and array_valid else (max(float(entry_array["high"]),float(sweep.get("extreme",entry_array["high"] if array_valid else 0)))+buffer) if direction=="bearish" and array_valid else None;target_price=target.get("price");risk=abs(entry-stop) if entry is not None and stop is not None else None;reward=abs(float(target_price)-entry) if target_price is not None and entry is not None else None;rr=reward/risk if risk and reward is not None else None;right_side=bool(target_price is not None and entry is not None and (float(target_price)>entry if direction=="bullish" else float(target_price)<entry));in_area=bool(array_valid and current_price is not None and float(entry_array["low"])<=float(current_price)<=float(entry_array["high"]));too_late=bool(entry is not None and current_price is not None and risk and abs(float(current_price)-entry)>risk)
    if direction not in {"bullish","bearish"}:state="NO_CONTEXT"
    elif not target:state="DIRECTIONAL_CONTEXT"
    elif not event_ok:state="WAITING_FOR_SWEEP"
    elif not displacement.get("passed"):state="WAITING_FOR_DISPLACEMENT"
    elif not confirmation:state="DISPLACEMENT_CONFIRMED"
    elif not array_valid:state="MSS_CONFIRMED"
    elif too_late:state="TOO_LATE"
    elif not in_area:state="WAITING_FOR_RETRACE"
    elif not (rr is not None and rr>=minimum_rr and right_side):state="WAITING_FOR_ENTRY_CONFIRMATION"
    else:state="TRADE_READY"
    identity=hashlib.sha256(json.dumps([symbol,strategy_id,direction,(confirmation or {}).get("structure_event_id"),entry_array.get("fvg_id") or entry_array.get("order_block_id"),entry,stop,target_price],sort_keys=True,default=str).encode()).hexdigest()[:24]
    next_required={"NO_CONTEXT":"Confirmed H1 directional structure.","DIRECTIONAL_CONTEXT":"A clean opposing structural target.","WAITING_FOR_TARGET":"A valid unswept structural target.","WAITING_FOR_SWEEP":"A qualified sweep or accepted continuation event.","WAITING_FOR_DISPLACEMENT":"Measurable completed-candle displacement.","DISPLACEMENT_CONFIRMED":"A completed MSS or BOS confirmation.","MSS_CONFIRMED":"A fresh family-supported entry array.","WAITING_FOR_RETRACE":"Price retracement into the selected entry array.","WAITING_FOR_ENTRY_CONFIRMATION":"Valid target geometry and minimum reward-to-risk.","TOO_LATE":"A new unextended setup.","TRADE_READY":"Paper analysis plan is complete."}.get(state,"Completed structural evidence.")
    targets=[{"name":"TP1","price":target_price,"risk_reward":rr,"target_id":target.get("target_id"),"source":target.get("source_type"),"timeframe":target.get("timeframe"),"scope":target.get("scope")}] if state=="TRADE_READY" and target_price is not None else []
    if state=="TRADE_READY" and secondary_target and secondary_target.get("price") is not None:
        targets.append({"name":"TP2","price":secondary_target["price"],"risk_reward":abs(float(secondary_target["price"])-entry)/risk if risk else None,"target_id":secondary_target.get("target_id"),"source":secondary_target.get("source_type"),"timeframe":secondary_target.get("timeframe"),"scope":secondary_target.get("scope")})
    return {"setup_id":"smc-"+identity,"strategy_id":strategy_id,"family_adapter":family_adapter,"direction":"buy" if direction=="bullish" else "sell" if direction=="bearish" else "","state":state,"htf_structure":htf_structure,"structural_target":target,"sweep":sweep,"displacement":displacement,"mss":structure.get("last_mss"),"bos":structure.get("last_bos"),"entry_array":entry_array,"entry":entry if state=="TRADE_READY" else None,"stop":stop if state=="TRADE_READY" else None,"targets":targets,"rr":rr if state=="TRADE_READY" else None,"projected_rr":rr,"next_required_condition":next_required,"invalidation_reason":None,"event_risk":event_risk,"research_only":bool(research_only)}
