"""Quality separates lifecycle progress from actual trade validity."""
def measure_candidate_quality(strategy_id,result,regime_confidence=0,data_status="good",research_only=False):
    decision=result.get("decision") or {};plan=result.get("active_trade_plan");zone=result.get("m15_setup_zone") or result.get("retest_zone");confirmation=result.get("confirmation") or {};rr=result.get("reward_risk") or {};chase=result.get("chase") or {};eligible=bool((result.get("strategy") or {}).get("eligible",True));blocks=[]
    if not eligible:blocks.append("Strategy-specific eligibility failed.")
    ready=bool(decision.get("trade_ready") and plan);rr_valid=bool(rr.get("valid") or plan and plan.get("tp1_rr") is not None and plan.get("tp1_rr")>=1);chase_valid=bool(chase.get("valid") or plan and plan.get("timing_state") not in {"TOO_LATE","MISSED","EXTENDED"})
    if ready and not all((plan.get("entry") is not None,plan.get("stop") is not None,plan.get("tp1"),rr_valid,chase_valid)):blocks.append("Trade-ready plan is incomplete.");ready=False
    components={"family_regime":min(1,float(regime_confidence or .5)),"setup_zone":.8 if zone and zone.get("valid",True) else .2,"confirmation":1 if confirmation.get("valid") else .35,"trade_plan":1 if ready else .25,"data":1 if data_status=="good" else .5,"contradictions":max(0,1-len(result.get("rejected_candidates",[]))*.05)}
    score=sum(components.values())/len(components);score=min(score,.65) if research_only else score;progress="entry available" if ready else "confirmed" if confirmation.get("valid") else "in setup zone" if result.get("m5_execution_zone") else "waiting for price" if zone else "context only";trade_quality="strong" if ready and score>=.8 else "acceptable" if ready else "weak" if zone else "insufficient";label="strong" if ready and score>=.8 else "qualified" if ready else "developing" if score>=.45 else "weak"
    selected=result.get("selected_candidate") or {};direction=decision.get("developing_direction") or selected.get("direction") or ""
    return {"strategy_id":strategy_id,"direction":direction,"candidate_state":decision.get("status",""),"trade_ready":ready,"quality_score":score,"quality_label":label,"setup_progress":progress,"trade_quality":trade_quality,"components":components,"blocking_reasons":blocks,"warnings":result.get("warnings",[]),"setup_id":decision.get("setup_id")}
