"""Single declarative registry for Derived Auto strategy eligibility."""
REGISTRY={
"volatility_structure_pullback":{"strategy_id":"volatility_structure_pullback","display_name":"Volatility Structure Pullback","supported_families":["VOLATILITY"],"supported_regimes":["TREND_BULLISH","TREND_BEARISH","PULLBACK_IN_BULLISH_TREND","PULLBACK_IN_BEARISH_TREND"],"restricted_regimes":["RANGE","COMPRESSION","UNSTABLE","POST_SPIKE"],"research_only":False,"enabled":True,"adapter":"structure_pullback","priority":30},
"derived_range_break_retest":{"strategy_id":"derived_range_break_retest","display_name":"Derived Range Breakout and Retest","supported_families":["VOLATILITY","RANGE_BREAK"],"supported_regimes":["COMPRESSION","BREAKOUT_ATTEMPT","ACCEPTED_BREAKOUT","EXPANSION","RANGE"],"restricted_regimes":["POST_SPIKE","UNSTABLE"],"research_only":False,"enabled":True,"adapter":"range_break_retest","priority":20},
"boom_crash_spike_state":{"strategy_id":"boom_crash_spike_state","display_name":"Boom/Crash Spike-State","supported_families":["BOOM","CRASH"],"supported_regimes":["*"],"restricted_regimes":[],"research_only":False,"enabled":True,"adapter":"boom_crash","priority":10},
"derived_range_reaction":{"strategy_id":"derived_range_reaction","display_name":"Derived Range Reaction","supported_families":["VOLATILITY","RANGE_BREAK"],"supported_regimes":["RANGE"],"restricted_regimes":["EXPANSION","ACCEPTED_BREAKOUT","BREAKOUT_ATTEMPT","UNSTABLE","POST_SPIKE"],"research_only":False,"enabled":True,"adapter":"range_reaction","priority":40},
"derived_switch_orchestrator":{"strategy_id":"derived_switch_orchestrator","display_name":"Derived Regime-Switch Orchestrator","supported_families":["VOLATILITY_SWITCH","DRIFT_SWITCH"],"supported_regimes":["*"],"restricted_regimes":[],"research_only":False,"enabled":True,"adapter":"switch","priority":10},
"jump_dex_post_event":{"strategy_id":"jump_dex_post_event","display_name":"Jump/DEX Post-Event Structure","supported_families":["JUMP","DEX"],"supported_regimes":["*"],"restricted_regimes":[],"research_only":True,"enabled":True,"adapter":"post_event","priority":10},
"step_structure_research":{"strategy_id":"step_structure_research","display_name":"Step Index Structure Research","supported_families":["STEP"],"supported_regimes":["*"],"restricted_regimes":[],"research_only":True,"enabled":True,"adapter":"step","priority":10}}
def derived_strategy_registry():return {key:dict(value) for key,value in REGISTRY.items()}
