def normalize_derived_auto(*,family,regime,data_gate,eligibility,candidates,selection,selected_result=None,historical_label="insufficient",continuity=None,market_context=None):
    selected=selection.get("selected_candidate");strategy_id=selected.get("strategy_id") if selected else None
    selected_funnel=(selected_result or {}).get("gate_funnel") or (selected or {}).get("gate_funnel") or {};best=selected or max(candidates,key=lambda row:row.get("passed_gate_count",(row.get("gate_funnel") or {}).get("passed_gate_count",0)),default=None);best_funnel=(best or {}).get("gate_funnel") or selected_funnel
    if not data_gate["passed"]:status="INSUFFICIENT HISTORY" if data_gate.get("missing_timeframes") else "LOADING MARKET CONTEXT";strategy_id=(best or {}).get("strategy_id")
    elif selected_result:status=selected_funnel.get("status") or (selected_result.get("decision") or {}).get("status","NO MARKET OPPORTUNITY")
    else:status=best_funnel.get("status") or ("STRATEGY INELIGIBLE" if not eligibility.get("eligible") else "NO MARKET OPPORTUNITY")
    source=(selected_result or {}).get("decision") or {};confidence=min(.95,float(selected.get("quality_score",0))) if selected else 0;research=bool((selected_result or {}).get("strategy_status")=="research" or (selected_result or {}).get("strategy",{}).get("status")=="research");confidence=min(confidence,.65) if research else confidence;label="high" if confidence>=.75 and source.get("trade_ready") and not research else "moderate" if confidence>=.5 else "low"
    direction=source.get("developing_direction","") if selected_result else (best or {}).get("direction","");decision={**source,"status":status,"strategy":strategy_id,"trade_ready":bool(source.get("trade_ready") and selected_result and not best_funnel.get("first_blocking_gate")),"setup_id":source.get("setup_id") if selected_result else None,"developing_direction":direction,"market_bias":source.get("market_bias",regime.get("direction","neutral")),"summary":status.title(),"setup_stage":best_funnel.get("setup_stage","context evaluation"),"first_blocking_gate":best_funnel.get("first_blocking_gate",""),"next_action":source.get("next_action") if selected_result and source.get("next_action") else best_funnel.get("next_price_condition","Wait for measurable completed-candle evidence.")}
    return {"router":{"name":"Derived Auto Strategy","requested_strategy":"Auto","family":family.get("family"),"regime":regime.get("regime"),"data_quality_passed":data_gate["passed"]},"evaluation":{"eligible_strategies":[row["strategy_id"] for row in eligibility["eligible"]],"ineligible_strategies":eligibility["ineligible"],"evaluated_candidates":candidates,"selected_strategy":strategy_id,"selected_candidate":selected,"selection_reason":f"{strategy_id} best fits the current measurable family, regime, and setup state." if strategy_id else "No strategy is currently eligible with meaningful setup evidence.","selection_confidence":confidence,"confidence_label":label,"confidence_reasons":["Selection reflects current regime and candidate completeness."],"confidence_limitations":["This is not guaranteed trade success."],"historical_evidence_label":historical_label},"decision":decision,"active_trade_plan":(selected_result or {}).get("active_trade_plan") if decision["trade_ready"] else None,"developing_scenario":None,"market_context":market_context or {},"previous_setup":(selected_result or {}).get("previous_setup"),"gate_funnel":best_funnel,"shadow_candidate":best_funnel.get("shadow_candidate"),"diagnostics":{"runner_up":selection.get("runner_up"),"conflicts":selection.get("conflicts",[]),"rejected_candidates":[row for row in candidates if row.get("blocking_reasons")],"gate_funnels":[row.get("gate_funnel") for row in candidates if row.get("gate_funnel")]},"continuity":continuity or {},"selected_result":selected_result,"research_mode":research,"validated_edge":False if research else None,"warnings":data_gate["warnings"]}
