"""Authoritative Derived Index research pipeline."""
from __future__ import annotations
import hashlib,json
import pandas as pd
from analysis.derived_family_classifier import classify_derived_family
from analysis.derived_market_profile import build_derived_market_profile
from analysis.synthetic_spike_detector import detect_synthetic_spike
from analysis.derived_regime_detector import detect_derived_regime
from analysis.derived_strategy_router import route_derived_strategies
from analysis.derived_context import build_derived_context
from analysis.derived_decision_normalizer import normalize_derived_decision
from analysis.synthetic_volatility import detect_synthetic_volatility
from analysis.derived_context import build_top_down_context,interpret_market
from analysis.derived_intelligence_normalizer import normalize_derived_intelligence
from strategies.derived.volatility_structure_pullback import evaluate_volatility_structure_pullback
from analysis.derived_strategy_decision import build_derived_trade_chart
from strategies.derived.range_break_retest import evaluate_derived_range_break_retest,ELIGIBLE_SECONDARY
from strategies.derived.boom_crash_spike_state import evaluate_boom_crash_spike_state
from strategies.derived.derived_range_reaction import evaluate_derived_range_reaction
from strategies.derived.derived_switch_orchestrator import evaluate_derived_switch
from strategies.derived.jump_dex_post_event import evaluate_jump_dex_post_event
from strategies.derived.step_structure_research import evaluate_step_structure_research
from strategies.derived.derived_auto_strategy import evaluate_derived_auto
from strategies.derived.base_derived_strategy import load_strategy_thresholds
from analysis.derived_strategy_gate_funnel import build_strategy_gate_funnel,archive_stale_range
from analysis.strategy_gate_diagnostics_store import StrategyGateDiagnosticsStore
from analysis.smc.smc_router import route_smc
from analysis.smc.smc_gate_funnel import build_smc_gate_funnel
from analysis.smc.smc_product_contract import build_smc_product_contract
from analysis.derived_model_compatibility import resolve_family_model
from analysis.strategy_reachability_gate import gate_normalized_auto_result
from analysis.strategy_reachability_gate import reachability_status
from analysis.strategy_reachability_gate import production_strategy_status
from analysis.strategy_reachability_gate import NO_VALIDATED_STRATEGY_MESSAGE
from analysis.strategy_quarantine_registry import is_auto_eligible, validation_entry
from analysis.volatility_structure_pullback_engine import evaluate_volatility_structure_pullback as evaluate_focused_volatility_pullback
from analysis.global_overlay_contract import normalize_global_decision

def analyze_derived_index(*,symbol,metadata,candles_by_timeframe,tick_size=.01,analysis_time=None,historical_evidence=None,requested_strategy="auto"):
    family=classify_derived_family(metadata or {"provider_symbol":symbol});m15=candles_by_timeframe.get("M15",pd.DataFrame());m5=candles_by_timeframe.get("M5",pd.DataFrame())
    profile=build_derived_market_profile(m15,family=family["family"],tick_size=tick_size,timeframe="M15",symbol=symbol)
    m5_profile=build_derived_market_profile(m5,family=family["family"],tick_size=tick_size,timeframe="M5",symbol=symbol);volatility=detect_synthetic_volatility(profile);spike=detect_synthetic_spike(m5,family=family["family"],atr=m5_profile.get("atr"),profile=m5_profile,expected_direction=family.get("expected_spike_direction"));regime=detect_derived_regime(m15,profile,spike,volatility,family["family"])
    quality=_quality(candles_by_timeframe,m5);current=float(m5.iloc[-1].close) if len(m5) else None;zone=None
    # This milestone exposes eligibility, not strategy evaluation. Keep the
    # legacy projection structurally compatible while preventing setup,
    # entry, risk, or target candidates from being generated.
    router={"requested_strategy":"Auto","eligible_strategies":[],"rejected_strategies":[],"selected_strategy":None,"selection_reason":"Market intelligence only; strategy evaluation is disabled.","selection_confidence":0.0,"bullish_candidate":{},"bearish_candidate":{},"selected_candidate":None,"strategy_results":[]}
    context=build_derived_context(timeframes={key:{"candles":len(value)} for key,value in candles_by_timeframe.items()},profile=profile,regime=regime,spike=spike,current_price=current)
    top_down=build_top_down_context(candles_by_timeframe,family["family"],tick_size);interpretation=interpret_market(family["family"],regime,volatility,spike);last=_last_completed(m5)
    intelligence=normalize_derived_intelligence(family=family,profile=profile,volatility=volatility,spike=spike,regime=regime,top_down=top_down,market_context=interpretation,data_quality=quality,last_completed_candle=last)
    focused_request=str(requested_strategy).lower() in {"auto","smc","smc_auto","volatility_smc","volatility_structure_pullback"}
    if family["family"]=="VOLATILITY" and focused_request:
        requested_model="smc_auto" if str(requested_strategy).lower() in {"auto","smc","smc_auto"} else str(requested_strategy).lower()
        contract=evaluate_focused_volatility_pullback(symbol=symbol,display_symbol=(metadata or {}).get("display_name") or symbol,candles_by_timeframe=candles_by_timeframe,tick_size=tick_size,analysis_time=analysis_time,profile={"mode":"balanced"},requested_model=requested_model,source_timeframe=(metadata or {}).get("source_timeframe") or "provided")
        contract["production_status"]=production_strategy_status("volatility_structure_pullback")
        # production_strategy_status() only knows raw fixture reachability,
        # not historical validation -- correct its stale auto_eligible before
        # this contract reaches any API response.
        contract["production_status"]["auto_eligible"]=is_auto_eligible("volatility_structure_pullback")
        contract["strategy_evidence"]=validation_entry("volatility_structure_pullback")
        if str(requested_strategy).lower()=="auto" and reachability_status("volatility_structure_pullback")!="REACHABLE":
            reason="Volatility Structure Pullback remains excluded from Auto until chronological setup proof reaches REACHABLE.";contract["decision"].update(status="PLAN REJECTED",headline="PLAN REJECTED",trade_ready=False,next_action=reason,first_blocking_gate="strategy_reachability");contract["setup"].update(trade_ready=False,entry=None,stop=None,targets=[],rr=None,research_only=True);contract["overlays"]=[row for row in contract["overlays"] if row.get("type") not in {"entry","stop","target"}];contract["reachability_gate"]={"strategy_id":"volatility_structure_pullback","status":reachability_status("volatility_structure_pullback"),"auto_eligible":False,"reason":reason}
        elif str(requested_strategy).lower()=="auto" and not is_auto_eligible("volatility_structure_pullback"):
            # Phase 6: reachable is not the same as historically validated --
            # Auto must never silently fall back to a rejected/unvalidated
            # strategy, even one that reached TRADE_READY.
            reason=NO_VALIDATED_STRATEGY_MESSAGE;contract["decision"].update(status="NO_VALIDATED_STRATEGY_AVAILABLE",headline="NO VALIDATED STRATEGY AVAILABLE",trade_ready=False,next_action=reason,first_blocking_gate="historical_validation");contract["setup"].update(trade_ready=False,entry=None,stop=None,targets=[],rr=None,research_only=True);contract["overlays"]=[row for row in contract["overlays"] if row.get("type") not in {"entry","stop","target"}];contract["reachability_gate"]={"strategy_id":"volatility_structure_pullback","status":reachability_status("volatility_structure_pullback"),"auto_eligible":False,"reason":reason,"blocking_gate":"historical_validation"}
        setup=contract["setup"];plan={"entry":setup.get("entry"),"stop":setup.get("stop"),"tp1":(setup.get("targets") or [None])[0],"tp1_rr":setup.get("rr"),"timing_state":"VALID","entry_type":"m5_displacement_retrace"} if contract["decision"]["trade_ready"] else None
        return {"decision":contract["decision"],"market_context":{"summary":contract["decision"]["summary"],"higher_timeframes":contract["market"]["external_structure"],"structure":contract["decision"]["summary"],"price_location":setup.get("stage"),"momentum":setup.get("direction")},"developing_scenario":{"available":bool(setup.get("direction")),"direction":setup.get("direction"),"label":contract["decision"]["status"],"strategy":"Volatility Structure Pullback","zone":setup.get("entry_area"),"required_event":setup.get("next_required_condition"),"confirmation_requirement":"Completed M5 displacement and internal structure break."},"active_trade_plan":plan,"key_levels":{"support":None,"resistance":((setup.get("projected_target") or {}).get("price")),"liquidity_above":None,"liquidity_below":None},"previous_setup":None,"advanced_details":{"router":contract["ownership"],"data_quality":quality,"family":family,"regime":regime,"strategy":contract},"market_profile":profile,"spike_state":spike,"intelligence":intelligence,"ownership":contract["ownership"],"gate_funnel":{"first_blocking_gate":contract["decision"].get("first_blocking_gate"),"setup_stage":setup.get("stage"),"status":contract["decision"]["status"]},"diagnostics":contract["diagnostics"],"strategy_result":contract,"m15_setup_zone":setup.get("entry_area"),"m5_execution_zone":setup.get("entry_area"),"confirmation":setup.get("completed_confirmation"),"trade_chart":{"current_price":contract["market"]["current_price"],"expected_entry":setup.get("entry_area"),"confirmation":{"price":((setup.get("completed_confirmation") or {}).get("broken_price")),"confirmed":bool(setup.get("completed_confirmation"))},"invalidation":{"price":setup.get("stop") or setup.get("projected_stop")},"targets":setup.get("targets") or ([setup["projected_target"]] if setup.get("projected_target") else [])},"product_contract":contract,"focused_production":True}
    smc_family=family["family"] in {"VOLATILITY","JUMP","STEP","STEP_CLASSIC","STEP_MULTI","STEP_SKEW_UP","STEP_SKEW_DOWN"};smc_request=str(requested_strategy).lower() in {"auto","smc","smc_auto","volatility_smc","jump_smc","step_smc"}
    if smc_family and smc_request:
        smc=route_smc(symbol=symbol,family=family,candles_by_timeframe=candles_by_timeframe,tick_size=tick_size,requested_strategy=requested_strategy,analysis_time=analysis_time);smc["trade_chart"]["current_price"]=current;history={key:len(candles_by_timeframe.get(key,[])) for key in ("D1","H4","H1","M15","M5")};funnel=build_smc_gate_funnel(smc,history);setup=smc["setup"];zone=smc.get("m15_setup_zone");target=setup.get("structural_target") or {};scenario={"available":bool(setup.get("direction")),"direction":setup.get("direction"),"label":smc["decision"]["status"],"strategy":smc["decision"]["strategy_label"],"zone":zone,"required_event":setup["next_required_condition"],"confirmation_requirement":"Completed causal M5 structure confirmation is required.","confirmation":"Completed causal M5 structure confirmation is required."};key_levels={"support":target.get("price") if target.get("type")=="sell_side" else None,"resistance":target.get("price") if target.get("type")=="buy_side" else None,"liquidity_above":target.get("price") if target.get("type")=="buy_side" else None,"liquidity_below":target.get("price") if target.get("type")=="sell_side" else None};smc.update({"market_context":{"summary":f"{smc['decision']['strategy_label']} · 24/7 UTC","higher_timeframes":smc["structure"].get("external_structure"),"structure":f"H1 {smc['structure'].get('external_structure')} / M15 {smc['structure'].get('internal_structure')}","price_location":setup.get("state"),"momentum":(setup.get("displacement") or {}).get("direction")},"developing_scenario":scenario,"key_levels":key_levels,"advanced_details":{"router":smc["ownership"],"data_quality":quality,"family":family,"regime":regime,"strategy":smc},"gate_funnel":funnel,"diagnostics":{"setup_gates":funnel},"market_profile":profile,"spike_state":spike,"intelligence":intelligence,"auto_router":{"family":family["family"],"selected_strategy":smc["ownership"]["selected_strategy_id"]},"auto_evaluation":{"selected_strategy":smc["ownership"]["selected_strategy_id"],"selection_reason":smc["ownership"]["selection_reason"],"evaluated_candidates":smc["evaluated_candidates"],"historical_evidence_label":"insufficient"} if str(requested_strategy).lower()=="auto" else None,"strategy_result":{"strategy":{"name":smc["decision"]["strategy_label"],"eligible":True,"eligibility_reason":smc["ownership"]["selection_reason"]},**smc},"confirmation":smc.get("confirmation")})
        smc["product_contract"]=build_smc_product_contract(symbol=symbol,display_symbol=family.get("display_name") or symbol,timeframe="M5",analysis_time=analysis_time or last,family=family,candles_by_timeframe=candles_by_timeframe,result=smc,live=True)
        return smc
    model_resolution=resolve_family_model(family["family"],requested_strategy)
    if model_resolution["corrected"]:requested_strategy=model_resolution["resolved_model"]
    use_range_break=family["family"]=="RANGE_BREAK" or family["family"]=="VOLATILITY" and regime.get("regime") in ELIGIBLE_SECONDARY
    if str(requested_strategy).lower()=="auto":
        auto=evaluate_derived_auto(symbol=symbol,family=family,regime=regime,profile=profile,volatility=volatility,spike=spike,candles_by_timeframe=candles_by_timeframe,current_price=current,tick_size=tick_size,data_quality=quality,analysis_time=analysis_time,historical_evidence=historical_evidence,market_context=interpretation,config=load_strategy_thresholds().get("derived_auto_router",{}));selected=auto.get("selected_result") or {};decision=auto["decision"];zone=selected.get("m15_setup_zone") or selected.get("retest_zone");execution=selected.get("m5_execution_zone") or selected.get("retest_zone");locked=selected.get("range") or {}
        if not zone and locked:zone={"low":locked.get("low"),"high":locked.get("high"),"type":"locked_range","valid":bool(locked)}
        scenario={"available":bool(zone),"direction":decision.get("developing_direction",""),"label":decision["status"],"strategy":auto["evaluation"].get("selected_strategy") or "","zone":zone,"required_event":decision.get("next_action",""),"confirmation_requirement":"The selected strategy retains its completed-candle confirmation gate.","confirmation":"The selected strategy retains its completed-candle confirmation gate."};key_levels=selected.get("key_levels") or {"support":locked.get("low"),"resistance":locked.get("high"),"liquidity_above":None,"liquidity_below":None};adapter={**selected,"m15_setup_zone":zone,"m5_execution_zone":execution,"decision":decision,"active_trade_plan":auto.get("active_trade_plan")}
        normalized={"decision":decision,"market_context":interpretation,"developing_scenario":scenario,"active_trade_plan":auto.get("active_trade_plan"),"key_levels":key_levels,"previous_setup":auto.get("previous_setup"),"advanced_details":{"router":auto["evaluation"],"data_quality":quality,"family":family,"regime":regime,"strategy":auto},"auto_router":auto["router"],"auto_evaluation":auto["evaluation"],"auto_diagnostics":auto["diagnostics"],"auto_continuity":auto["continuity"],"m15_setup_zone":zone,"m5_execution_zone":execution,"confirmation":selected.get("confirmation"),"strategy_result":selected,"trade_chart":build_derived_trade_chart(adapter,current)}
    elif str(requested_strategy).lower()=="step_structure_research":
        strategy=evaluate_step_structure_research(symbol=symbol,family=family,profile=profile,candles_by_timeframe=candles_by_timeframe,current_price=current,tick_size=tick_size,data_quality=quality,analysis_time=analysis_time);delegated=strategy.get("delegated_result") or {};decision={**strategy["decision"],"strategy":"step_structure_research","regime":strategy["regime"]["regime"]};zone=strategy.get("m15_setup_zone");execution=strategy.get("m5_execution_zone");scenario={"available":bool(zone),"direction":decision.get("developing_direction",""),"label":decision["status"],"strategy":"Step Index Structure Research","zone":zone,"required_event":"Price must reach the selected research area without sequence chasing.","confirmation_requirement":"Completed M5 confirmation is required.","confirmation":"Completed M5 confirmation is required."};normalized={"decision":decision,"market_context":interpretation,"developing_scenario":scenario,"active_trade_plan":strategy.get("active_trade_plan"),"key_levels":delegated.get("key_levels") or {"support":None,"resistance":None,"liquidity_above":None,"liquidity_below":None},"previous_setup":strategy.get("previous_setup"),"advanced_details":{"router":strategy["routing"],"data_quality":quality,"family":family,"regime":strategy["regime"],"strategy":strategy},"step_profile":strategy["step_profile"],"step_sequence":strategy["sequence"],"routing":strategy["routing"],"m15_setup_zone":zone,"m5_execution_zone":execution,"confirmation":strategy.get("confirmation"),"strategy_result":strategy,"trade_chart":build_derived_trade_chart({**delegated,"decision":decision,"active_trade_plan":strategy.get("active_trade_plan")},current)}
    elif str(requested_strategy).lower()=="jump_dex_post_event":
        strategy=evaluate_jump_dex_post_event(symbol=symbol,family=family,profile=profile,candles_by_timeframe=candles_by_timeframe,current_price=current,tick_size=tick_size,data_quality=quality,analysis_time=analysis_time);decision={**strategy["decision"],"strategy":"jump_dex_post_event","regime":regime["regime"]};zone=strategy.get("m15_setup_zone");execution=strategy.get("m5_execution_zone");event=strategy.get("event") or {}
        scenario={"available":bool(zone),"direction":decision.get("developing_direction",""),"label":decision["status"],"strategy":"Jump/DEX Post-Event Structure","zone":zone,"required_event":"Fresh structure must form after the latest locked event.","confirmation_requirement":"A completed post-zone M5 structure break is required.","confirmation":"A completed post-zone M5 structure break is required."};key_levels={"support":event.get("origin_price") if event.get("direction")=="up" else None,"resistance":event.get("origin_price") if event.get("direction")=="down" else None,"liquidity_above":event.get("extreme_price") if event.get("direction")=="up" else None,"liquidity_below":event.get("extreme_price") if event.get("direction")=="down" else None};trade_chart=build_derived_trade_chart(strategy,current);trade_chart.update({"event_origin":event.get("origin_price"),"event_extreme":event.get("extreme_price"),"event_direction":event.get("direction")})
        normalized={"decision":decision,"market_context":interpretation,"developing_scenario":scenario,"active_trade_plan":strategy.get("active_trade_plan"),"key_levels":key_levels,"previous_setup":strategy.get("previous_setup"),"advanced_details":{"router":router,"data_quality":quality,"family":family,"regime":regime,"strategy":strategy},"event":strategy.get("event"),"cooldown":strategy.get("cooldown"),"post_event_volatility":strategy.get("post_event_volatility"),"post_event_structure":strategy.get("post_event_structure"),"event_hold":strategy.get("event_hold"),"m15_setup_zone":zone,"m5_execution_zone":execution,"confirmation":strategy.get("confirmation"),"strategy_result":strategy,"trade_chart":trade_chart}
    elif str(requested_strategy).lower()=="derived_regime_switch":
        strategy=evaluate_derived_switch(symbol=symbol,family=family,regime=regime,profile=profile,volatility=volatility,candles_by_timeframe=candles_by_timeframe,current_price=current,tick_size=tick_size,data_quality=quality,analysis_time=analysis_time)
        delegated=strategy.get("delegated_result") or {};decision={**strategy["decision"],"strategy":"derived_regime_switch","regime":strategy["switch_context"].get("current_regime")};zone=delegated.get("m15_setup_zone") or delegated.get("retest_zone");execution=delegated.get("m5_execution_zone") or delegated.get("retest_zone");route=strategy["routing"]
        scenario={"available":bool(zone),"direction":decision.get("developing_direction",""),"label":decision["status"],"strategy":"Derived Regime Switch","zone":zone,"required_event":"The completed-candle regime must stabilize before strategy delegation.","confirmation_requirement":"The delegated strategy retains its own confirmation requirements.","confirmation":"The delegated strategy retains its own confirmation requirements."}
        normalized={"decision":decision,"market_context":interpretation,"developing_scenario":scenario,"active_trade_plan":strategy.get("active_trade_plan"),"key_levels":delegated.get("key_levels") or {"support":None,"resistance":None,"liquidity_above":None,"liquidity_below":None},"previous_setup":strategy.get("previous_setup"),"advanced_details":{"router":route,"data_quality":quality,"family":family,"regime":regime,"strategy":strategy},"switch_context":strategy["switch_context"],"regime_stability":strategy["regime_stability"],"transition":strategy["transition"],"routing":route,"risk_adjustments":strategy["risk_adjustments"],"m15_setup_zone":zone,"m5_execution_zone":execution,"confirmation":delegated.get("confirmation"),"strategy_result":strategy,"trade_chart":build_derived_trade_chart(delegated,current) if delegated else build_derived_trade_chart({"decision":decision},current)}
    elif str(requested_strategy).lower()=="derived_range_reaction":
        strategy=evaluate_derived_range_reaction(symbol=symbol,family=family,regime=regime,profile=profile,volatility=volatility,candles_by_timeframe=candles_by_timeframe,current_price=current,tick_size=tick_size,data_quality=quality,analysis_time=analysis_time)
        decision={**strategy["decision"],"strategy":"derived_range_reaction","regime":regime["regime"]};locked=strategy.get("range") or {};zone=strategy.get("m15_setup_zone");execution=strategy.get("m5_execution_zone")
        scenario={"available":bool(zone),"direction":decision.get("developing_direction",""),"label":decision["status"],"strategy":"Derived Range Reaction","zone":zone,"required_event":"Price must interact with a qualified locked-range boundary.","confirmation_requirement":"A completed M5 rejection and post-reaction structure break are required.","confirmation":"A completed M5 rejection and post-reaction structure break are required."}
        key_levels={"support":locked.get("low"),"resistance":locked.get("high"),"liquidity_above":None,"liquidity_below":None}
        normalized={"decision":decision,"market_context":interpretation,"developing_scenario":scenario,"active_trade_plan":strategy.get("active_trade_plan"),"key_levels":key_levels,"previous_setup":strategy.get("previous_setup"),"advanced_details":{"router":router,"data_quality":quality,"family":family,"regime":regime,"strategy":strategy},"range":locked,"boundary_quality":strategy.get("boundary_quality"),"boundary_pressure":strategy.get("boundary_pressure"),"price_location":strategy.get("price_location"),"boundary_rejection":strategy.get("boundary_rejection"),"m15_setup_zone":zone,"m5_execution_zone":execution,"confirmation":strategy.get("confirmation"),"strategy_result":strategy,"trade_chart":build_derived_trade_chart(strategy,current)}
    elif family["family"] in {"BOOM","CRASH"}:
        strategy=evaluate_boom_crash_spike_state(symbol=symbol,family=family,spike_detector=spike,volatility=volatility,profile=profile,candles_by_timeframe=candles_by_timeframe,current_price=current,tick_size=tick_size,data_quality=quality,analysis_time=analysis_time)
        decision={**strategy["decision"],"strategy":"boom_crash_spike_state","regime":regime["regime"]};zone=strategy.get("m15_setup_zone");execution=strategy.get("m5_execution_zone")
        scenario={"available":bool(zone),"direction":decision.get("developing_direction",""),"label":decision["status"],"strategy":"Boom/Crash Spike-State","zone":zone,"required_event":"Cooldown must release and fresh post-spike structure must reach the selected area.","confirmation_requirement":"A completed post-zone M5 structure break is required.","confirmation":"A completed post-zone M5 structure break is required."}
        key_levels={"support":zone.get("low") if zone and decision.get("developing_direction")=="buy" else None,"resistance":zone.get("high") if zone and decision.get("developing_direction")=="sell" else None,"liquidity_above":None,"liquidity_below":None}
        normalized={"decision":decision,"market_context":interpretation,"developing_scenario":scenario,"active_trade_plan":strategy.get("active_trade_plan"),"key_levels":key_levels,"previous_setup":strategy.get("previous_setup"),"advanced_details":{"router":router,"data_quality":quality,"family":family,"regime":regime,"strategy":strategy},"spike":strategy.get("spike"),"cooldown":strategy.get("cooldown"),"post_spike_structure":strategy.get("post_spike_structure"),"m15_setup_zone":zone,"m5_execution_zone":execution,"confirmation":strategy.get("confirmation"),"strategy_result":strategy,"trade_chart":build_derived_trade_chart(strategy,current)}
    elif use_range_break:
        strategy=evaluate_derived_range_break_retest(symbol=symbol,family=family,regime=regime,profile=profile,candles_by_timeframe=candles_by_timeframe,current_price=current,tick_size=tick_size,data_quality=quality,analysis_time=analysis_time)
        decision={**strategy["decision"],"strategy":"derived_range_break_retest","regime":regime["regime"]};locked=strategy.get("range") or {};retest=strategy.get("retest_zone")
        scenario={"available":bool(locked),"direction":decision.get("developing_direction",""),"label":decision["status"],"strategy":"Derived Range Breakout and Retest","zone":retest or ({"low":locked.get("low"),"high":locked.get("high"),"type":"locked_range"} if locked else None),"required_event":"A completed accepted breakout must retest its locked boundary.","confirmation_requirement":"A completed post-retest M5 structure break is required.","confirmation":"A completed post-retest M5 structure break is required."}
        key_levels={"support":locked.get("low"),"resistance":locked.get("high"),"liquidity_above":None,"liquidity_below":None};adapter={**strategy,"m15_setup_zone":{"low":locked.get("low"),"high":locked.get("high"),"type":"locked_range","valid":bool(locked)},"m5_execution_zone":retest}
        normalized={"decision":decision,"market_context":interpretation,"developing_scenario":scenario,"active_trade_plan":strategy.get("active_trade_plan"),"key_levels":key_levels,"previous_setup":strategy.get("previous_setup"),"advanced_details":{"router":router,"data_quality":quality,"family":family,"regime":regime,"strategy":strategy},"range":locked,"breakout":strategy.get("breakout"),"retest_zone":retest,"m5_execution_zone":retest,"confirmation":strategy.get("confirmation"),"strategy_result":strategy,"trade_chart":build_derived_trade_chart(adapter,current)}
    elif family["family"]=="VOLATILITY":
        strategy=evaluate_volatility_structure_pullback(symbol=symbol,family=family,regime=regime,top_down=top_down,profile=profile,candles_by_timeframe=candles_by_timeframe,current_price=current,tick_size=tick_size,data_quality=quality,analysis_time=analysis_time)
        decision={**strategy["decision"],"strategy":"volatility_structure_pullback","regime":regime["regime"]}
        scenario={"available":bool(strategy.get("m15_setup_zone")),"direction":decision.get("developing_direction",""),"label":decision["status"],"strategy":"Volatility Structure Pullback","zone":strategy.get("m15_setup_zone"),"required_event":"Price reaches the selected M15 pullback area.","confirmation_requirement":"A completed post-interaction M5 structure break is required.","confirmation":"A completed post-interaction M5 structure break is required."}
        normalized={"decision":decision,"market_context":interpretation,"developing_scenario":scenario,"active_trade_plan":strategy.get("active_trade_plan"),"key_levels":strategy["key_levels"],"previous_setup":strategy.get("previous_setup"),"advanced_details":{"router":router,"data_quality":quality,"family":family,"regime":regime,"strategy":strategy},"pullback":strategy["pullback"],"m15_setup_zone":strategy.get("m15_setup_zone"),"m5_execution_zone":strategy.get("m5_execution_zone"),"confirmation":strategy.get("confirmation"),"strategy_result":strategy,"trade_chart":build_derived_trade_chart(strategy,current)}
    else:normalized=normalize_derived_decision(symbol=symbol,family=family,regime=regime,router=router,market_context=context,data_quality=quality,zone=zone,current_price=current,timestamp=analysis_time)
    strategy_id=(normalized.get("decision") or {}).get("strategy") or str(requested_strategy).lower();result=normalized.get("strategy_result") or normalized;funnel=normalized.get("gate_funnel") or build_strategy_gate_funnel(strategy_id,result,family=family,regime=regime,data_quality=quality,frames=candles_by_timeframe,current_price=current)
    if funnel.get("stale_setup_state"):funnel["archived_stale_setups"]=archive_stale_range(symbol,result,analysis_time)
    if strategy_id=="jump_dex_post_event" and not result.get("event"):funnel.update(status="NO CURRENT POST-EVENT SETUP",setup_stage="waiting for qualified event",next_price_condition="Wait for a qualified completed-candle Jump/DEX event.")
    if strategy_id=="step_structure_research":funnel["selected_step_sub_method"]=(result.get("routing") or {}).get("delegated_sub_strategy") or "None"
    normalized["gate_funnel"]=funnel;normalized["shadow_candidate"]=funnel.get("shadow_candidate");normalized.setdefault("diagnostics",{})["setup_gates"]=funnel
    decision=normalized.get("decision") or {}
    if not decision.get("trade_ready") or funnel.get("first_blocking_gate"):decision.update(status=funnel["status"],setup_stage=funnel["setup_stage"],first_blocking_gate=funnel["first_blocking_gate"],next_action=funnel["next_price_condition"],trade_ready=False);normalized["active_trade_plan"]=None
    normalized["decision"]=decision;normalized["market_profile"]=profile;normalized["spike_state"]=spike;normalized["intelligence"]=intelligence;normalized["model_resolution"]=model_resolution
    normalized=gate_normalized_auto_result(normalized,family["family"],requested_strategy)
    if not bool(__import__('os').environ.get("PYTEST_CURRENT_TEST")):
        try:StrategyGateDiagnosticsStore().record(symbol=symbol,family=family.get("family",""),strategy=strategy_id,regime=regime.get("regime",""),funnel=funnel,day=str(pd.Timestamp(analysis_time).date()) if analysis_time is not None else None)
        except (OSError,ValueError):pass
    normalized["product_contract"]=_global_product_from_derived(normalized,symbol=symbol,metadata=metadata or {},family=family,current=current,quality=quality,analysis_time=analysis_time,tick_size=tick_size)
    return normalized

def _global_product_from_derived(normalized,*,symbol,metadata,family,current,quality,analysis_time,tick_size):
    public=normalized.get("decision") or {};plan=normalized.get("active_trade_plan") or {};strategy_id=str(public.get("strategy") or "derived_context");direction=public.get("developing_direction") or public.get("direction");direction=direction if direction in {"buy","sell"} else None;setup_id=public.get("setup_id") or plan.get("setup_id");zone=normalized.get("m15_setup_zone") or normalized.get("retest_zone");ready=bool(public.get("trade_ready") and plan and setup_id and direction)
    def target(value,name):
        if isinstance(value,dict):return {"name":name,"price":value.get("price"),"risk_reward":value.get("risk_reward") or value.get("projected_rr"),"source":value.get("source") or value.get("source_type")}
        return {"name":name,"price":value} if value is not None else None
    targets=[row for row in (target(plan.get("tp1"),"TP1"),target(plan.get("tp2"),"TP2")) if row and row.get("price") is not None]
    stage="TRADE_READY" if ready else str(public.get("setup_stage") or public.get("stage") or public.get("status") or "NO_CONTEXT").upper().replace(" ","_");entry=plan.get("entry") if ready else None;stop=plan.get("stop") if ready else None;rr=plan.get("tp1_rr") or plan.get("rr") if ready else None
    setup={"setup_id":setup_id,"setup_type":public.get("setup_type") or strategy_id,"strategy_id":strategy_id,"direction":direction,"stage":stage,"state":stage,"trade_ready":ready,"entry":entry,"stop":stop,"targets":targets if ready else [],"rr":rr,"entry_area":zone if setup_id else None,"completed_confirmation":normalized.get("confirmation") if ready else None,"next_required_condition":public.get("next_action"),"first_blocking_gate":public.get("first_blocking_gate"),"production_supported":bool((normalized.get("production_status") or {}).get("production_supported",not public.get("research_only"))),"family_compatible":True,"chase_valid":plan.get("timing_state") not in {"TOO_LATE","CHASED"}}
    owner={"selection_mode":"auto","requested_model_id":strategy_id,"selected_model_id":strategy_id,"selected_strategy_id":strategy_id,"decision_owner_id":strategy_id,"overlay_owner_id":strategy_id,"family_adapter_id":family.get("family")};rows=[]
    def add(kind,price=None,low=None,high=None,setup_owner=None,name=None,state="active"):
        rows.append({"overlay_id":"derived-"+hashlib.sha256(json.dumps([symbol,strategy_id,setup_owner,kind,price,low,high],default=str).encode()).hexdigest()[:20],"owner_id":strategy_id,"setup_id":setup_owner,"type":kind,"price":price,"low":low,"high":high,"name":name or kind.replace("_"," ").title(),"state":state,"source":"derived_family_adapter"})
    if current is not None:add("current_price",price=current,name="Current Price")
    levels=normalized.get("key_levels") or {}
    for key,label in (("support","Structural Support"),("resistance","Structural Resistance"),("liquidity_above","Opposing Liquidity"),("liquidity_below","Opposing Liquidity")):
        if levels.get(key) is not None:add("liquidity_reference" if "liquidity" in key else "structural_reference",price=levels[key],name=label)
    range_=normalized.get("range") or {}
    if range_.get("low") is not None and range_.get("high") is not None:add("structural_range",low=range_["low"],high=range_["high"],name="Active Range")
    if setup_id and zone and zone.get("low") is not None and zone.get("high") is not None:add("setup_area",low=zone["low"],high=zone["high"],setup_owner=setup_id,name="DEVELOPING · NOT AN ENTRY")
    confirmation=normalized.get("confirmation") or {};confirmation_price=confirmation.get("price") or confirmation.get("level") or confirmation.get("trigger")
    if setup_id and confirmation_price is not None:add("confirmation_level",price=confirmation_price,setup_owner=setup_id,name="MONITORING LEVEL")
    if ready:
        add("entry",price=entry,setup_owner=setup_id,name="Entry",state="confirmed");add("stop",price=stop,setup_owner=setup_id,name="Stop",state="confirmed")
        for row in targets:add("target",price=row["price"],setup_owner=setup_id,name=row["name"],state="confirmed")
    product={"decision_id":"derived-decision-"+hashlib.sha256(json.dumps([symbol,str(analysis_time),strategy_id,setup_id,stage],default=str).encode()).hexdigest()[:24],"meta":{"symbol":symbol,"display_symbol":metadata.get("display_name") or symbol,"timeframe":"M5","analysis_time":str(analysis_time),"market_source":"deriv","market_type":"derived","family":family.get("family"),"live":quality.get("analysis_allowed",False),"market_schedule":"24_7","analysis_clock":"UTC"},"ownership":owner,"readiness":{"state":"ready" if quality.get("analysis_allowed") else "insufficient","warnings":quality.get("warnings") or []},"market":{"external_structure":((normalized.get("market_context") or {}).get("higher_timeframes")),"internal_structure":((normalized.get("market_context") or {}).get("structure")),"current_price":current},"decision":{"status":public.get("status") or "NO MARKET OPPORTUNITY","direction":direction,"setup_type":setup.get("setup_type"),"stage":stage,"headline":public.get("status") or "NO MARKET OPPORTUNITY","summary":((normalized.get("market_context") or {}).get("summary")),"next_action":public.get("next_action"),"first_blocking_gate":public.get("first_blocking_gate"),"trade_ready":ready},"setup":setup,"diagnostics":normalized.get("diagnostics") or {},"overlays":rows,"previous_setup":normalized.get("previous_setup"),"paper_analysis_only":True}
    return normalize_global_decision(product,instrument_metadata={**metadata,"tick_size":metadata.get("tick_size") or tick_size},mode="LIVE")

def _last_completed(rows):
    if rows is None or rows.empty:return None
    completed=rows[rows.complete.astype(bool)] if "complete" in rows else rows
    if completed.empty:return None
    value=completed.iloc[-1].time
    return value.isoformat() if hasattr(value,"isoformat") else str(value)

def _quality(frames,m5):
    missing=[key for key in ("D1","H4","H1","M15","M5") if key not in frames or frames[key].empty];metadata=getattr(m5,"attrs",{}).get("time_metadata",{});last=str(m5.iloc[-1].time) if len(m5) else None
    status="invalid" if missing else "partial" if metadata.get("missing_intervals") else "good"
    return {"status":status,"last_tick_time":last,"missing_intervals":metadata.get("missing_intervals",[]),"duplicate_count":metadata.get("duplicate_count",0),"out_of_order_count":metadata.get("out_of_order_count",0),"history_depth":{key:len(value) for key,value in frames.items()},"analysis_allowed":not missing,"warnings":[f"Missing history: {', '.join(missing)}"] if missing else metadata.get("warnings",[])}
def _zone(rows,regime):
    if rows is None or len(rows)<5:return None
    recent=rows.tail(10);direction=regime.get("direction");return {"low":float(recent.low.min()),"high":float(recent.low.quantile(.35)),"type":"demand","timeframe":"M15"} if direction=="bullish" else {"low":float(recent.high.quantile(.65)),"high":float(recent.high.max()),"type":"supply","timeframe":"M15"} if direction=="bearish" else None
def _location(price,rows):
    if price is None or rows is None or rows.empty:return "unavailable"
    low=float(rows.tail(20).low.min());high=float(rows.tail(20).high.max());position=(price-low)/max(high-low,1e-12);return "near_low" if position<.2 else "near_high" if position>.8 else "mid_range"
