"""Adapt the existing Forex/Crypto/Index decision without changing its logic."""
from __future__ import annotations
import hashlib,json
from analysis.forex_decision_normalizer import enforce_forex_invariants
from analysis.global_overlay_contract import normalize_global_decision

def _normalize_market_decision(legacy,*,symbol,display_symbol,timeframe,market_source,market_type,market_schedule,analysis_time,live=True):
    setup=legacy.get("setup") or {};execution=legacy.get("execution") or {};quality=legacy.get("quality") or {};output=legacy.get("user_output") or {};routing=legacy.get("strategy_routing") or {};top=legacy.get("top_down") or {};ready=bool(quality.get("trade_plan_valid"));direction=setup.get("direction") or (output.get("direction") or "").lower();direction=direction if direction in {"buy","sell"} else None
    owner=routing.get("selected_strategy") or legacy.get("primary_strategy") or "structure_context";setup_id=setup.get("setup_id");state=str(execution.get("state") or setup.get("stage") or "none");decision_id=legacy.get("decision_id") or "market-decision-"+hashlib.sha256(json.dumps([symbol,str(analysis_time),setup_id,state,owner],default=str).encode()).hexdigest()[:24]
    frames=(legacy.get("candle_bundle") or {}).get("timeframes") or {};readiness_frames={key:{"available":int((value or {}).get("available_count") or len((value or {}).get("candles") or [])),"required":0,"passed":bool((value or {}).get("valid",True)),"last_completed_time":(value or {}).get("last_completed_time")} for key,value in frames.items()};data_state="ready" if quality.get("data_quality")!="invalid" else "error"
    trade_chart=legacy.get("trade_chart") or {};zone=setup.get("zone") or {};chart_zone=trade_chart.get("expected_entry") or trade_chart.get("m15_setup_zone") or {};zone_low=zone.get("low") if zone.get("low") is not None else chart_zone.get("low");zone_high=zone.get("high") if zone.get("high") is not None else chart_zone.get("high");targets=execution.get("targets") or [];normalized_targets=[{"name":row.get("name",f"TP{i+1}"),"price":row.get("price"),"risk_reward":row.get("risk_reward"),"source":row.get("source") or row.get("reason"),"timeframe":row.get("timeframe") or row.get("source_timeframe")} for i,row in enumerate(targets) if row.get("price") is not None]
    normalized_setup={"setup_id":setup_id,"setup_type":setup.get("type") or setup.get("setup_type"),"family_adapter":owner,"direction":direction,"stage":state,"status":output.get("status") or "NO VALID SETUP","context_summary":output.get("summary") or str((legacy.get("alignment") or {}).get("message") or "Completed top-down market context."),"next_required_condition":output.get("next_action") or execution.get("message") or "Wait for completed confirmation.","first_blocking_gate":execution.get("blocker"),"trade_ready":ready,"entry":execution.get("entry") if ready else None,"stop":execution.get("stop") if ready else None,"targets":normalized_targets if ready else [],"rr":execution.get("risk_reward") if ready else None,"invalidation":{"price":(setup.get("invalidation") or {}).get("price") or execution.get("stop"),"condition":setup.get("invalidation_context") or "Structural context invalidates"},"entry_area":{"low":zone_low,"high":zone_high,"type":zone.get("type") or chart_zone.get("type") or "setup_area"} if zone_low is not None and zone_high is not None else None,"quality_score":quality.get("score",0),"quality_grade":_grade(quality.get("score",0))}
    overlays=_overlays(legacy.get("overlays"),owner,setup_id,trade_chart)
    market_structure=legacy.get("top_down") or {}
    return {"decision_id":decision_id,"meta":{"symbol":symbol,"display_symbol":display_symbol,"timeframe":timeframe,"analysis_time":str(analysis_time),"market_source":market_source,"market_type":market_type,"live":bool(live),"market_schedule":market_schedule,"analysis_clock":"UTC"},"ownership":{"selection_mode":"auto" if routing.get("selected_strategy") else "manual","requested_model_id":legacy.get("requested_strategy") or "auto","selected_model_id":owner,"decision_owner_id":owner,"overlay_owner_id":owner,"family_adapter_id":owner,"selection_reason":routing.get("reason","")},"readiness":{"state":data_state,"source":market_source,"as_of":str(analysis_time),"timeframes":readiness_frames,"warnings":[]},"market":{"external_structure":((market_structure.get("H1") or {}).get("structure")),"internal_structure":((market_structure.get("M15") or {}).get("structure")),"current_price":(legacy.get("trade_chart") or {}).get("current_price"),"session":((legacy.get("filters") or {}).get("session") or {}).get("name")},"decision":{"status":output.get("status") or "NO VALID SETUP","direction":direction,"setup_type":normalized_setup["setup_type"],"stage":state,"headline":output.get("status") or "NO VALID SETUP","summary":normalized_setup["context_summary"],"next_action":normalized_setup["next_required_condition"],"first_blocking_gate":execution.get("blocker"),"trade_ready":ready},"setup":normalized_setup,"diagnostics":{"invariants":legacy.get("answer_validation") or {"valid":True},"gate_funnel":legacy.get("router") or {},"target_trace":(legacy.get("liquidity_targets") or {}).get("target_trace") or {}},"overlays":overlays,"previous_setup":legacy.get("previous_setup"),"paper_analysis_only":True,"legacy_contract":legacy}

def normalize_market_decision(legacy,*,symbol,display_symbol,timeframe,market_source,market_type,market_schedule,analysis_time,live=True):
    product=_normalize_market_decision(legacy,symbol=symbol,display_symbol=display_symbol,timeframe=timeframe,market_source=market_source,market_type=market_type,market_schedule=market_schedule,analysis_time=analysis_time,live=live)
    product=enforce_forex_invariants(product,legacy) if market_type=="forex" else product
    return normalize_global_decision(product,mode="LIVE" if live else "REPLAY")

def _grade(score):
    value=float(score or 0);return "A" if value>=90 else "B" if value>=80 else "C" if value>=70 else "REJECTED"

def _overlays(source,owner,setup_id,trade_chart):
    if isinstance(source,list):return [{**row,"owner_id":owner,"setup_id":row.get("setup_id") or setup_id,"visibility_category":row.get("visibility_category") or "trade_plan"} for row in source]
    rows=[]
    def level(key,name,kind,price,state="conditional"):
        if price is not None:rows.append({"overlay_id":f"{owner}-{key}","owner_id":owner,"setup_id":setup_id,"visibility_category":"trade_plan","type":kind,"state":state,"price":price,"name":name})
    level("current","Current","current_price",trade_chart.get("current_price"),"active")
    area=trade_chart.get("expected_entry") or trade_chart.get("m15_setup_zone") or {}
    if area.get("low") is not None and area.get("high") is not None:rows.append({"overlay_id":f"{owner}-entry-area","owner_id":owner,"setup_id":setup_id,"visibility_category":"trade_plan","type":"entry_area","state":"active","low":area["low"],"high":area["high"],"name":"Expected Entry"})
    confirmation=trade_chart.get("confirmation") or {};level("confirmation","M5 Confirmation","confirmation",confirmation.get("price"),"confirmed" if confirmation.get("confirmed") else "conditional")
    invalidation=trade_chart.get("invalidation") or {};level("invalidation","Stop Loss" if confirmation.get("confirmed") else "Idea Invalidation","stop",invalidation.get("price"))
    for index,target in enumerate(trade_chart.get("targets") or []):
        if target.get("valid",True):level(f"target-{index}",target.get("name") or f"TP{index+1}","target",target.get("price"),"confirmed" if confirmation.get("confirmed") else "conditional")
    return rows
