from analysis.derived_execution_confirmation import build_m5_execution_zone
def build_step_execution_zone(candles,direction,m15_zone,zone_reached_at=None):return build_m5_execution_zone(candles,direction,m15_zone,zone_reached_at)
